# Generated by Django 4.0.6 on 2022-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltask',
            name='objectives',
        ),
        migrations.AddField(
            model_name='globaltask',
            name='objectives',
            field=models.ManyToManyField(related_name='tasks', to='tasks.objectives'),
        ),
    ]
