# Generated by Django 4.0.5 on 2022-07-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('cart_order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='position',
        ),
        migrations.AddField(
            model_name='cart',
            name='position',
            field=models.ManyToManyField(to='catalog.product'),
        ),
    ]
