# Generated by Django 4.0.5 on 2022-07-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('cart_order', '0005_remove_cart_count_remove_order_cart_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='position',
            field=models.ManyToManyField(related_name='item', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='position',
            field=models.ManyToManyField(related_name='items', to='catalog.product'),
        ),
    ]
