# Generated by Django 4.0.5 on 2022-06-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('made_in', models.CharField(max_length=50)),
                ('model_years', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('founded', models.DateTimeField()),
                ('headquaters', models.CharField(max_length=50)),
                ('logo', models.FileField(blank=True, null=True, upload_to='uploads/logo_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('carbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_catalog.carbasemodel')),
                ('displacement', models.CharField(max_length=5)),
                ('fuel_type', models.CharField(max_length=20)),
                ('torque', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('fuel_consumption', models.CharField(max_length=20)),
            ],
            bases=('car_catalog.carbasemodel',),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('carbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='car_catalog.carbasemodel')),
                ('layout', models.CharField(max_length=50)),
                ('body_style', models.IntegerField()),
                ('prestige', models.CharField(max_length=50, verbose_name='Class')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photo_models')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='car_catalog.carbrand', verbose_name='')),
                ('engine', models.ManyToManyField(related_name='engines', to='car_catalog.engine')),
            ],
            bases=('car_catalog.carbasemodel',),
        ),
    ]
