# Generated by Django 4.0.5 on 2022-06-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='prestige',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='clasification',
            field=models.CharField(choices=[('A', 'City car'), ('B', 'Supemini'), ('C', 'Compact'), ('D', 'Mid-size'), ('E', 'Executiv'), ('F', 'Luxary'), ('S', 'Sport'), ('M', 'MPV'), ('J', 'SUV')], default=2000, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carbasemodel',
            name='made_in',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('SW', 'Sweden')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carbasemodel',
            name='model_years',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='founded',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='body_style',
            field=models.CharField(choices=[('CAB', 'Cabriolet'), ('COU', 'Coupe'), ('HB', 'Hatchback'), ('S', 'Sedan'), ('SW', 'Station wagon'), ('MVP', 'Minivan'), ('PT', 'Pickup truck'), ('T', 'Truck')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='car_catalog.carbrand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='layout',
            field=models.CharField(choices=[('FWD', 'Front-wheel drive'), ('RWD', 'Rear-wheel drive'), ('4WD', 'Four-wheel drive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='engine',
            name='fuel_type',
            field=models.CharField(choices=[('El', 'Electric'), ('D', 'Diesel'), ('GAS', 'Gasoline'), ('NG', 'Natural gas'), ('H', 'Hybrid')], max_length=20),
        ),
    ]
