# Generated by Django 4.0.5 on 2022-06-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_catalog', '0002_remove_carmodel_prestige_carmodel_clasification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
